In [12]:
import numpy as np
import sys

In [16]:
a = np.array([1,2],dtype='int16')

In [8]:
a.ndim

1

In [9]:
a.shape

(4,)

In [10]:
a.dtype

dtype('int16')

In [19]:
a.nbytes

4

In [24]:
b = np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
print(b[:,2])

[ 3 33]


In [55]:
c = np.random.randint(-50,50,size=(2,2))
print(c)

[[-14  40]
 [ -8 -37]]


In [59]:
ques = np.ones((5,5))
ques[1:4,1:4]=0
ques[2,2]=9
ques

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
a=np.array([[1,2,3],[4,5,6]])
b=a.copy()
b[0,0]=10
a[1,0]=20
print(a)
print(b)

[[ 1  2  3]
 [20  5  6]]
[[10  2  3]
 [ 4  5  6]]
